/*******************************************************************************
 * This code is distributed under GPL v2 licence.
 * 
 * This code is provided solely "as is". 
 * There is no warranty or other guarantee of fitness of this code.
 * The author disclaims all responsibility and liability 
 * with respect to this code's usage
 * or its effect upon hardware or computer systems.
 * 
 * author: Huu-Nghia Nguyen
 * email : nhnghia@me.com
 ******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. ExpressionReaderConstants.java */
package fr.lri.schora.expr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int RELATION_OPERATION = 8;
  /** RegularExpression Id. */
  int COMPUTATION_OPERATION_1 = 9;
  /** RegularExpression Id. */
  int COMPUTATION_OPERATION_2 = 10;
  /** RegularExpression Id. */
  int IDENT = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int STRING = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<TRUE>",
    "<FALSE>",
    "<RELATION_OPERATION>",
    "<COMPUTATION_OPERATION_1>",
    "<COMPUTATION_OPERATION_2>",
    "<IDENT>",
    "<CONST>",
    "<INT>",
    "<STRING>",
    "\"(\"",
    "\")\"",
  };

}
