/* Generated By:JavaCC: Do not edit this line. STGReaderConstants.java */
package fr.lri.schora.stg.dot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface STGReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LABEL = 10;
  /** RegularExpression Id. */
  int CONNECT = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int LPARAM = 13;
  /** RegularExpression Id. */
  int RPARAM = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;
  /** RegularExpression Id. */
  int IDENT = 17;
  /** RegularExpression Id. */
  int STRING = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "\"label\"",
    "\"->\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"\\\"\"",
    "<IDENT>",
    "<STRING>",
  };

}
