/* Generated By:JavaCC: Do not edit this line. ChorReaderConstants.java */
package fr.lri.schora.chorD.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ChorReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SKIPP = 10;
  /** RegularExpression Id. */
  int LPARAM = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int EVENT = 13;
  /** RegularExpression Id. */
  int RPARAM = 14;
  /** RegularExpression Id. */
  int CONDITION = 15;
  /** RegularExpression Id. */
  int LOOP = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int PARALLEL = 18;
  /** RegularExpression Id. */
  int CHOICE = 19;
  /** RegularExpression Id. */
  int SEQUENCE = 20;
  /** RegularExpression Id. */
  int INTERRUP = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int EVENTS = 23;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 24;

  /** Lexical state. */
  int IN_EVENT = 0;
  /** Lexical state. */
  int IN_GUARD = 1;
  /** Lexical state. */
  int IN_CONDITION = 2;
  /** Lexical state. */
  int IN_COMMENT = 3;
  /** Lexical state. */
  int DEFAULT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "\"skip\"",
    "\"[\"",
    "\"(\"",
    "<EVENT>",
    "\"]\"",
    "<CONDITION>",
    "\"*\"",
    "\"|>\"",
    "\"|\"",
    "\"+\"",
    "\";\"",
    "\"[>\"",
    "\")\"",
    "<EVENTS>",
    "<UNEXPECTED_CHAR>",
  };

}
